version: "3.4"

volumes:
  odoodata:
  pgdata:

x-logging:
  &default-logging
  driver: local
  options:
    max-size: "10m"
    max-file: "5"

services:
  db:
    image: docker.io/postgres:13
    logging: *default-logging
    restart: "no"
    environment:
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_DB=postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432
  odoo:
    image: odoo:dev-16.0
    build: .
    command: /opt/src/submodules/ocb/odoo-bin -c /etc/odoo/odoo.conf
    logging: *default-logging
    restart: "no"
    depends_on:
      - db
    volumes:
      - odoodata:/var/lib/odoo
      - .:/opt/src
      - ./odoo.conf:/etc/odoo/odoo.conf

  web:
    image: nginx
    logging: *default-logging
    restart: "no"
    command: >
      /bin/sh -c
      "envsubst '$$SERVER_NAME $$HTTP_PORT'
      < /etc/nginx/conf.d/nginx_odoo_proxy.conf.tpl
      > /etc/nginx/conf.d/odoo.conf
      && rm -f /etc/nginx/conf.d/default.conf
      && nginx -g 'daemon off;'"
    environment:
      SERVER_NAME: localhost
      HTTP_PORT: 8016
    volumes:
      - ./nginx_odoo_proxy.conf.tpl:/etc/nginx/conf.d/nginx_odoo_proxy.conf.tpl
    ports:
      - 8016:80
    depends_on:
      - odoo

  util:
    image: odoo:dev-16.0
    build: .
    logging: *default-logging
    command: "true"
    volumes:
      - .:/opt/src
      - ./scripts/from_container/black-and-pretty:/usr/local/bin/black-and-pretty
      - ./scripts/from_container/backup:/usr/local/bin/backup
      - ./scripts/from_container/restore:/usr/local/bin/restore
      - odoodata:/var/lib/odoo
      - pgdata:/var/lib/postgresql/data
      - ./backups:/backups
