#!/bin/bash
set -euo pipefail

readonly SCRIPT_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" &>/dev/null && pwd -P)
export PATH=$SCRIPT_DIR:$PATH
readonly REPO_DIR=$(realpath "$SCRIPT_DIR/..")
readonly ODOODB=${1:?Missing required parameter odoo db name}

cd "$REPO_DIR"
black-and-pretty "$REPO_DIR/addons"

sudo docker-compose down
sudo docker-compose up -d web db
readonly DEV_ADDONS=$(ls addons | tr '\n' ,)
sudo docker-compose run odoo /opt/src/submodules/ocb/odoo-bin \
     -c /etc/odoo/odoo.conf \
     --stop-after-init \
     --no-http \
     -d $ODOODB \
     -u $DEV_ADDONS
sudo docker-compose up -d odoo
sudo docker-compose logs -f --tail 10 odoo
